name = "flow-api"
main = "src/worker.js"
compatibility_date = "2026-08-27"

[build]
command = "npm run build"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "flow-api"
database_id = "a0da54db-fb97-4a3c-87ac-e6a3ea214773"

[triggers]
crons = ["0 0 * * *"] # Run daily at midnight UTC
