name = "gden-flow"
main = "src/worker.js"
compatibility_date = "2026-08-27"

[build]
command = "npm run build"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "data-d1"
database_id = "550df1a1-503f-4d11-a901-d99264520f30"

[triggers]
crons = ["0 0 * * *"] # Run daily at midnight UTC
